/**
 * Generate build-time version env for Vite.
 * Only updates VITE_APP_VERSION, VITE_COMMIT_HASH, VITE_BUILD_TIME in .env files.
 * Preserves all other variables (VITE_API_URL, VITE_CLOUDFLARE_SITE_KEY, etc.) – never overwrites whole file.
 */
import { execSync } from 'child_process';
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const frontendRoot = join(__dirname, '..');
const gitRoot = join(frontendRoot, '..');

function runGit(cmd, defaultValue) {
  try {
    return execSync(cmd, {
      encoding: 'utf8',
      cwd: gitRoot,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
  } catch {
    return defaultValue;
  }
}

function getTimestampVersion() {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `v${y}.${m}.${day}`;
}

function getVersion() {
  const tag = runGit('git describe --tags --abbrev=0', null);
  if (tag && tag.length) return tag;
  const hash = runGit('git rev-parse --short HEAD', null);
  if (hash && hash.length) return hash;
  return getTimestampVersion();
}

const VITE_APP_VERSION = getVersion();
const VITE_COMMIT_HASH = runGit('git rev-parse --short HEAD', 'n/a');
const VITE_BUILD_TIME = new Date().toISOString();

const VERSION_KEYS = ['VITE_APP_VERSION', 'VITE_COMMIT_HASH', 'VITE_BUILD_TIME'];
const VERSION_COMMENT = '# Auto-generated by scripts/generate-version.js';

function isVersionLine(line) {
  const trimmed = line.trim();
  if (!trimmed) return false;
  if (trimmed.startsWith(VERSION_COMMENT)) return true;
  return VERSION_KEYS.some((k) => trimmed.startsWith(k + '='));
}

/**
 * Merge version into existing content: remove old version lines, append new block.
 * Keeps all other lines (including comments and user vars) unchanged.
 */
function mergeVersionIntoContent(existingContent) {
  const lines = (existingContent || '').split(/\r?\n/);
  const otherLines = lines.filter((line) => !isVersionLine(line));
  const trimmedEnd = otherLines.join('\n').replace(/\n+$/, '');
  const versionBlock = [
    '',
    VERSION_COMMENT + ' – do not edit by hand',
    `VITE_APP_VERSION=${VITE_APP_VERSION}`,
    `VITE_COMMIT_HASH=${VITE_COMMIT_HASH}`,
    `VITE_BUILD_TIME=${VITE_BUILD_TIME}`,
  ].join('\n');
  return (trimmedEnd + versionBlock + '\n').replace(/\n{3,}/g, '\n\n');
}

// Chỉ cập nhật version vào các file này; không đụng .env.production / .env.development (giữ nguyên cấu hình của bạn)
const files = ['.env', '.env.local', '.env.production.local'];
for (const file of files) {
  const filePath = join(frontendRoot, file);
  let content;
  try {
    if (existsSync(filePath)) {
      const existing = readFileSync(filePath, 'utf8');
      content = mergeVersionIntoContent(existing);
    } else {
      content = [
        VERSION_COMMENT + ' – do not edit by hand',
        `VITE_APP_VERSION=${VITE_APP_VERSION}`,
        `VITE_COMMIT_HASH=${VITE_COMMIT_HASH}`,
        `VITE_BUILD_TIME=${VITE_BUILD_TIME}`,
      ].join('\n') + '\n';
    }
    writeFileSync(filePath, content, 'utf8');
    console.log(`[version] Updated ${file}`);
  } catch (e) {
    try {
      mkdirSync(dirname(filePath), { recursive: true });
      content = [
        VERSION_COMMENT + ' – do not edit by hand',
        `VITE_APP_VERSION=${VITE_APP_VERSION}`,
        `VITE_COMMIT_HASH=${VITE_COMMIT_HASH}`,
        `VITE_BUILD_TIME=${VITE_BUILD_TIME}`,
      ].join('\n') + '\n';
      writeFileSync(filePath, content, 'utf8');
      console.log(`[version] Created ${file}`);
    } catch (e2) {
      console.warn(`[version] Skip ${file}:`, e2.message);
    }
  }
}

console.log(`[version] VITE_APP_VERSION=${VITE_APP_VERSION} VITE_COMMIT_HASH=${VITE_COMMIT_HASH}`);
