/**
 * Generate build-time version env for Vite.
 * Writes VITE_APP_VERSION, VITE_COMMIT_HASH, VITE_BUILD_TIME.
 * Robust fallback: tag -> commit hash as version -> timestamp version (vYYYY.MM.DD) when no .git.
 */
import { execSync } from 'child_process';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const frontendRoot = join(__dirname, '..');
const gitRoot = join(frontendRoot, '..');

function runGit(cmd, defaultValue) {
  try {
    return execSync(cmd, {
      encoding: 'utf8',
      cwd: gitRoot,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
  } catch {
    return defaultValue;
  }
}

/** Timestamp version when no git (e.g. v2026.02.10). Better than 0.0.0 for debugging. */
function getTimestampVersion() {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `v${y}.${m}.${day}`;
}

function getVersion() {
  const tag = runGit('git describe --tags --abbrev=0', null);
  if (tag && tag.length) return tag;
  const hash = runGit('git rev-parse --short HEAD', null);
  if (hash && hash.length) return hash;
  return getTimestampVersion();
}

function getCommitHash() {
  return runGit('git rev-parse --short HEAD', 'n/a');
}

function getBuildTime() {
  return new Date().toISOString();
}

const VITE_APP_VERSION = getVersion();
const VITE_COMMIT_HASH = getCommitHash();
const VITE_BUILD_TIME = getBuildTime();

const content = [
  '# Auto-generated by scripts/generate-version.js – do not edit by hand',
  `VITE_APP_VERSION=${VITE_APP_VERSION}`,
  `VITE_COMMIT_HASH=${VITE_COMMIT_HASH}`,
  `VITE_BUILD_TIME=${VITE_BUILD_TIME}`,
].join('\n') + '\n';

const files = ['.env', '.env.local', '.env.production.local'];
for (const file of files) {
  const filePath = join(frontendRoot, file);
  try {
    writeFileSync(filePath, content, 'utf8');
    console.log(`[version] Wrote ${file}`);
  } catch (e) {
    try {
      mkdirSync(dirname(filePath), { recursive: true });
      writeFileSync(filePath, content, 'utf8');
      console.log(`[version] Wrote ${file}`);
    } catch (e2) {
      console.warn(`[version] Could not write ${file}:`, e2.message);
    }
  }
}

console.log(`[version] VITE_APP_VERSION=${VITE_APP_VERSION} VITE_COMMIT_HASH=${VITE_COMMIT_HASH}`);
