/**
 * Generate build-time version env file from Git.
 * Writes VITE_APP_VERSION, VITE_COMMIT_HASH, VITE_BUILD_TIME to .env.local and .env.production.local.
 * Run from frontend directory (npm run dev / npm run build).
 */
import { execSync } from 'child_process';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
/** Frontend dir (where .env.local is written). */
const frontendRoot = join(__dirname, '..');
/** Git repo root (parent of frontend, so tags/commits are available). */
const gitRoot = join(frontendRoot, '..');

function runGit(cmd, defaultValue) {
  try {
    return execSync(cmd, {
      encoding: 'utf8',
      cwd: gitRoot,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
  } catch {
    return defaultValue;
  }
}

function getVersion() {
  const tag = runGit('git describe --tags --abbrev=0', null);
  if (tag && tag.length) return tag;
  return '0.0.0';
}

function getCommitHash() {
  return runGit('git rev-parse --short HEAD', 'dev');
}

function getBuildTime() {
  return new Date().toISOString();
}

const VITE_APP_VERSION = getVersion();
const VITE_COMMIT_HASH = getCommitHash();
const VITE_BUILD_TIME = getBuildTime();

const content = [
  '# Auto-generated by scripts/generate-version.js – do not edit by hand',
  `VITE_APP_VERSION=${VITE_APP_VERSION}`,
  `VITE_COMMIT_HASH=${VITE_COMMIT_HASH}`,
  `VITE_BUILD_TIME=${VITE_BUILD_TIME}`,
].join('\n') + '\n';

const files = ['.env.local', '.env.production.local'];
for (const file of files) {
  const filePath = join(frontendRoot, file);
  try {
    writeFileSync(filePath, content, 'utf8');
    console.log(`[version] Wrote ${file}`);
  } catch (e) {
    try {
      mkdirSync(dirname(filePath), { recursive: true });
      writeFileSync(filePath, content, 'utf8');
      console.log(`[version] Wrote ${file}`);
    } catch (e2) {
      console.warn(`[version] Could not write ${file}:`, e2.message);
    }
  }
}

console.log(`[version] VITE_APP_VERSION=${VITE_APP_VERSION} VITE_COMMIT_HASH=${VITE_COMMIT_HASH}`);
